non fixable error

diff --git a/basics_1/0-change_your_home_IP b/basics_1/0-change_your_home_IP
--- a/basics_1/0-change_your_home_IP
+++ b/basics_1/0-change_your_home_IP
@@ -1,24 +1,23 @@
 #!/usr/bin/env bash
 # my comment
 
-# Backup original hosts file
+if [ "$EUID" -ne 0 ]; then
+  echo "Please run as root"
+  exit 1
+fi
+
+# Backup hosts file just in case
 cp /etc/hosts /etc/hosts.bak
 
-# Replace localhost IP without using sed -i
+# Use sed to replace localhost IP inline, output to temp file
+sed 's/^127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts | \
+  grep -v 'facebook\.com' > /tmp/hosts.tmp
 
-# Create a temp file with the replacement for localhost line
-awk '
-  $1 == "127.0.0.1" && $2 == "localhost" {
-    $1 = "127.0.0.2"
-  }
-  { print }
-' /etc/hosts > /tmp/hosts.tmp
+# Append facebook.com mapping to temp file
+echo '8.8.8.8 facebook.com' >> /tmp/hosts.tmp
 
-# Overwrite /etc/hosts by moving temp file
-mv /tmp/hosts.tmp /etc/hosts
+# Now safely overwrite /etc/hosts by copying the contents back (not by replacing file)
+cat /tmp/hosts.tmp > /etc/hosts
 
-# Remove any existing facebook.com line
-grep -v "facebook.com" /etc/hosts > /tmp/hosts.tmp && mv /tmp/hosts.tmp /etc/hosts
-
-# Append facebook.com line
-echo "8.8.8.8 facebook.com" >> /etc/hosts
+# Clean up temp file
+rm /tmp/hosts.tmp
